const images = {
	menu: require("./menu.png"),
	slider1: require("./login1.png"),
	slider2: require("./login2.png"),
	logo: require("./logo.png"),
	login: require("./login.png"),
	carShield: require("./car-shield.png"),
	planeShield: require("./plane-shield.png"),
	language: require("./language.png"),
	carHand: require("./car-hand.png"),
	planeHand: require("./plane-hand.png"),
	userChecked: require("./user-checked.png"),
	carChecked: require("./car-checked.png"),
	flag: require("./flag.png"),
	calendar: require("./calendar.png"),
	umbrellaCoin: require("./umbrella-coin.png"),
	ladyWorking: require("./lady-working.png"),
	handHoldingCard: require("./hand-holding-car.png"),
	shield: require("./shield.png"),
	gray: require("./gray.jpg"),
	logoBg: require("./logo-bg.png"),
};
export default images;
