export const INIT_USER_STATE = "INIT_USER_STATE";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOADED = "USER_LOADED";
export const CUSTOMER_LOADED = "CUSTOMER_LOADED";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const SET_PIN_CODE = "SET_PIN_CODE";
export const SET_LANGUAGE = "SET_LANGUAGE";

export const PROFILE_STORED = "PROFILE_STORED";
export const PROFILE_LOAD_REDUX = "PROFILE_LOAD_REDUX";

export const SET_DEVICE_TOKEN = "SET_DEVICE_TOKEN";
export const SOS_LIST_UPDATE = "SOS_LIST_UPDATE";

export const TOGGLE_MENU = "TOGGLE_MENU";
export const SHOW_FLASH_MESSAGE = "SHOW_FLASH_MESSAGE";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const SHOW_SELECTION_LOADING = "SHOW_SELECTION_LOADING";
export const HIDE_SELECTION_LOADING = "HIDE_SELECTION_LOADING";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const SET_INSURANCE_DATA = "SET_INSURANCE_DATA";
export const REMOVE_INSURANCE_DATA = "SET_INSURANCE_DATA";
export const SET_CURRENT_STEP = "SET_CURRENT_STEP";
export const SET_INSURANCE_COST = "SET_INSURANCE_COST";
export const SET_ANTI_COVID = "SET_ANTI_COVID";
export const REFRESH_INCURANCE = "REFRESH_INCURANCE";

export const SET_DOCUMENTS = "SET_DOCUMENTS";
export const SET_PERSONAL_INFO = "SET_PERSONAL_INFO";
export const SET_INSURANCE_PERIOD = "SET_INSURANCE_PERIOD";
export const SET_LOCATION_INFO = "SET_LOCATION_INFO";
export const SET_SHIPPING_INFO = "SET_SHIPPING_INFO";
export const SET_WITH_SHIPPING = "SET_WITH_SHIPPING";
export const SET_SHIPPING_ADDRESS_SAME = "SET_SHIPPING_ADDRESS_SAME";

//mapState
export const SET_MY_LOCATION = "SET_MY_LOCATION";
export const SET_HELP_LOCATION = "SET_HELP_LOCATION";

export type AppState = {
	menuOpen: boolean;
	flashMessage: string;
	flashMessageType: string;
};
