export const TOGGLE_MENU = "TOGGLE_MENU";
export const SHOW_FLASH_MESSAGE = "SHOW_FLASH_MESSAGE";

export const SHOW_SELECTION_LOADING = "SHOW_SELECTION_LOADING";
export const HIDE_SELECTION_LOADING = "HIDE_SELECTION_LOADING";

export const SET_INSURANCE_DATA = "SET_INSURANCE_DATA";
export const REMOVE_INSURANCE_DATA = "SET_INSURANCE_DATA";
export const SET_CURRENT_STEP = "SET_CURRENT_STEP";
export const SET_INSURANCE_COST = "SET_INSURANCE_COST";

export const SET_DOCUMENTS = "SET_DOCUMENTS";
export const SET_PERSONAL_INFO = "SET_PERSONAL_INFO";
export const SET_INSURANCE_PERIOD = "SET_INSURANCE_PERIOD";
export const SET_LOCATION_INFO = "SET_LOCATION_INFO";
export const SET_SHIPPING_INFO = "SET_SHIPPING_INFO";

export type AppState = {
	menuOpen: boolean;
	flashMessage: string;
	flashMessageType: string;
};
